#!/bin/bash
ISPL_TOOLS=../../../ispltools/tools/
PYTHON=python3
FIRMWARE_IMG=release-firmware/ckt-xing-basic-49ce4400-1Jan2025.sbp

# if less than two arguments supplied, display usage 
if [  $# -ge 1 ] 
then 
	echo "Usage: ./program-bootloader"
	exit 1
fi 


while [ true ]
do
	espeak "Switch to AVR"
	read -p "Set switch to AVR and press any key to program..."
	echo -e "\n\033[1;33mProgramming Bootloader\033[0m\n"
	espeak "Programming bootloader"
	make -C ./bootloader/ fuse
	make -C ./bootloader/ flash
	make -C ./bootloader/ reset
	if [ $? -eq 0 ]
	then 
		echo -e "\033[0;32mSuccess\033[0m\n"
		espeak "Switch to flash"
	else 
		echo -e "\033[0;31mFailed\033[0m\n"
		espeak "Failed"
		continue
	fi

	read -p "Set switch to FLASH and press any key to program..."
	echo -e "\n\033[1;33mProgramming Flash\033[0m\n"
	espeak "Programming flash"
	$PYTHON $ISPL_TOOLS/spiflash-pyprog/flash.py $FIRMWARE_IMG
	if [ $? -eq 0 ]
	then 
		echo -e "\033[0;32mComplete\033[0m\n"
		espeak "Complete"
	else 
		echo -e "\033[0;31mFailed\033[0m\n"
		espeak "Failed"
		continue
	fi


	
	sleep 1

done
