#!/bin/bash

# if less than two arguments supplied, display usage 
if [  $# -ge 1 ] 
then 
	echo "Usage: ./program-bootloader"
	exit 1
fi 


while [ true ]
do
	make read > /dev/null 2> /dev/null

	while [ $? -ne 0 ]
	do
		echo -n .
		make read > /dev/null 2> /dev/null
	done

	echo -e "\n\033[1;33mProgramming\033[0m\n"
	espeak "Programming"
	make fuse
	make flash
	make reset
	if [ $? -eq 0 ]
	then 
		echo -e "\033[0;32mComplete\033[0m\n"
		espeak "Complete"
	else 
		echo -e "\033[0;31mFailed\033[0m\n"
		espeak "Failed"
	fi
	
	sleep 1

done
