#ifndef _TIME_CONFIG_H_
#define _TIME_CONFIG_H_

#define DECISECS_DETECTION_MINIMUM_ON          20
#define DECISECS_DETECTION_APPROACH_TIMEOUT   200
#define DECISECS_DETECTION_LOCKOUT_TIMEOUT    200

#define DECISECS_SIGNAL_MAIN_GATE_DELAY        20
#define DECISECS_SIGNAL_MAIN_GATE_DROP         30

#define DECISECS_SIGNAL_4Q_GATE_DELAY          20
#define DECISECS_SIGNAL_4Q_GATE_DROP           30
#define DECISECS_SIGNAL_4Q_GATE_RISE_DELAY     10

#define DECISECS_SIGNAL_GATE_RISE              20

#endif
